name: vitepress-theme-curve
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 22.16.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.16
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.11.1

      - run: pnpm install
      - run: pnpm run docs:build
      - run: ls -la .vitepress/dist  

      - name: Deploy to Workers
        uses: cloudflare/wrangler-action@3.0.0
        with:
          command: pages deploy .vitepress/dist --project-name vitepress-theme-curve
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}